---
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
install_traffic_ops: False
to_pkg_name: "{% if to_version is defined and to_version != omit %}{{ 'traffic_ops-'+to_version }}{% else %}traffic_ops{% endif %}"

# Postgres Superuser account to use with TO database and user creation
postgresql_admin_user:
postgresql_admin_user_password:
postgresql_client_pkg_name: "{% if pg_major_version | int < 10 %}postgresql{{pg_major_version}}{{pg_minor_version}}-{{pg_major_version}}.{{pg_minor_version}}.{{pg_build_num}}{% else %}postgresql{{pg_major_version}}-{{pg_major_version}}.{{pg_minor_version}}{% endif %}"

# Local OS Account to use with TrafficOps processes
to_user: trafops # currently hardcoded into TO
to_group: trafops # currently hardcoded into TO

# TO Installation information
to_base_installdir: /opt/traffic_ops
to_app_installdir: "{{ to_base_installdir }}/app"
to_db_installdir: "{{ to_app_installdir }}/db"
to_conf_installdir: "{{ to_app_installdir }}/conf"
to_install_installdir: "{{ to_base_installdir }}/install"
to_install_json_installdir: "{{ to_install_installdir }}/data/json"
to_install_bin_installdir: "{{ to_install_installdir }}/bin"

# URL users should use to reach TO
to_url: "https://{{ ansible_fqdn }}"

# Initial TO Administrative User
to_admin_user:
to_admin_user_password:

# --- cdn.conf
to_disable_auto_cert_deletion: false
to_use_ims: true
to_use_rbp: true
to_user_cache_refresh_interval_sec: 0
to_server_update_status_cache_refresh_interval_sec: 0
to_hypnotoad_number_of_workers: 12
to_cors_access_control_allow_origin: "http://localhost:8080"
to_base_url: https://localhost
to_secrets:
  - your-custom-secret1
  - your-custom-secret2

to_certs_cert: /etc/pki/tls/certs/localhost.crt
to_certs_key: /etc/pki/tls/private/localhost.key
to_certs_ca: /etc/pki/ca-trust/source/anchors/root.ca.crt
to_certs_verify: "0x00"

to_inactivity_timeout: 120
to_influxdb_conf_path: "{{ to_conf_installdir }}/influxdb.conf"
to_gen_new_secret: "yes"
to_no_of_secrets_to_keep: "2"

to_portal_base_url: "http://localhost:8080"
to_portal_docs_url: "https://traffic-control-cdn.readthedocs.io/en/latest/admin/traffic_portal/usingtrafficportal.html#usingtrafficportal"
to_portal_email_from: "TrafficControl <no-reply@trafficcontrol.apache.org>"
to_portal_pass_reset_path: user
to_portal_user_register_path: user/register
to_email_from: "{{ to_portal_email_from }}"
to_account_missing_msg: "Could not locate user."

to_mojo_max_db_connections: 20
to_go_max_db_connections: 20
to_go_inactive_timeout: 120
to_go_logging_file_debug: ""
to_go_logging_file_event: /var/log/traffic_ops/access.log
to_go_logging_file_info: /var/log/traffic_ops/info.log
to_go_logging_file_warn: /var/log/traffic_ops/error.log
to_go_logging_file_error: /var/log/traffic_ops/error.log
to_go_db_max_idle_connections: 15
to_go_db_conn_max_lifetime_seconds: 600
to_go_db_query_timeout_seconds: 300
to_go_port: 443
to_go_proxy_keep_alive: 0
to_go_proxy_read_header_timeout: 120
to_go_proxy_timeout: 120
to_go_proxy_tls_timeout: 120
to_go_read_header_timeout: 120
to_go_read_timeout: 120
to_go_write_timeout: 120
to_go_supported_ds_metrics:
  - kbps
  - tps_total
  - tps_2xx
  - tps_3xx
  - tps_4xx
  - tps_5xx

to_go_client_auth_enabled: 0
to_go_whitelisted_oauth_urls: ""
to_go_oauth_user_attribute: ""
to_go_oauth_client_secret: ""

to_client_cert_root_directory: "/etc/pki/tls/traffic_ops/"

to_plugin_config: {}

to_le_user_email: user@example.test
to_le_send_expiration_email: false
to_le_convert_self_signed: false
to_le_renew_days_before_expiration: 30
to_le_environment: production

to_traffic_vault_backend: "postgres"

to_smtp_enabled: false
to_smtp_username: ""
to_smtp_password: ""
to_smtp_address: ""

# --- database.conf & dbconf.yml
todb_db_name: traffic_ops
todb_type: Pg
todb_port: 5432
todb_host: localhost
todb_username:
todb_password:
todb_ssl_enable: false
todb_dbconf:
  production:
    driver: postgres
    host: localhost
    port: 5432
    user: "{{ todb_username }}"
    password: "{{ todb_password }}"
    dbname: "{{ todb_db_name }}"
    sslmode: disable
    open_manual: ""

# --- Traffic Vault Postgres backend traffic_vault_config (in cdn.conf) & dbconf.yml
to_tvdb_db_name: traffic_vault
to_tvdb_type: Pg
to_tvdb_port: 5432
to_tvdb_host: localhost
to_tvdb_username:
to_tvdb_password:
to_tvdb_ssl_enable: false
to_tvdb_aes_key_loc: "{{ to_conf_installdir }}/aes.key"
to_tvdb_aes_key:
to_tvdb_dbconf:
  production:
    driver: postgres
    host: localhost
    port: 5432
    user: "{{ to_tvdb_username }}"
    password: "{{ to_tvdb_password }}"
    dbname: "{{ to_tvdb_db_name }}"
    sslmode: disable
    open_manual: ""


# --- postinstall - input.json
to_pi_script_with_args: "{{ to_pi_script }} -a -cfile {{ to_pi_input_json }}"
to_pi_script: "{{ to_install_bin_dir }}/postinstall"
to_pi_maxmind_download: "yes"
to_pi_add_custom_profiles: "no"

# --- postinstall - SSL Certs
to_pi_openssl_generate_certificate: "yes"
to_pi_openssl_country_name: "US"
to_pi_openssl_state_or_province: "CO"
to_pi_openssl_locality_name: "Denver"
to_pi_openssl_org_name: "TrafficControl"
to_pi_openssl_unit_name: "CDN"
to_pi_openssl_common_name: "{{ ansible_hostname }}"
to_pi_openssl_rsa_passphrase:

# --- postinstall profiles.json
to_pi_cdn_name: "{{ hostvars[groups['traffic_router'] | first].cdn | default('mkga') | lower }}"
to_pi_health_polling_interval: "8000"
to_pi_dns_subdomain: "{{ to_pi_cdn_name }}.{{ ansible_domain }}"
to_pi_soa_admin: "traffic_ops"
to_pi_driver_prefix: "/dev/sd"
to_pi_ram_drive_prefix: "/dev/ram"
to_pi_ram_drive_letters: "0,1,2,3,4,5,6,7"
to_pi_health_thresh_load_avg: "25"
to_pi_health_thresh_kbps: "1750000"
to_pi_health_connect_timeout: "2000"

# --- influxdb.conf
to_influxdb_user: "influxuser"
to_influxdb_password: "password"
to_influxdb_deliveryservice_stats_db_name: "delivery_stats"
to_influxdb_cache_stats_db_name: "cache_stats"
to_influxdb_secure: false

# --- log4perl.conf
to_log_file: "/var/log/traffic_ops/traffic_ops.log"

# --- ldap.conf
to_ldap_setup: "no"
to_ldap_hostname: ""
to_ldap_admin_dn: ""
to_ldap_password: ""
to_ldap_search_base: ""
to_ldap_search_query: ""
to_ldap_insecure: 0
to_ldap_timeout_secs: ""

# --- riak.conf
to_riak_conf: "{{ to_config_dir }}/riak.conf"
to_riak_username:
to_riak_username_password:
to_riak_tls_max_version: "1.1"
to_riak_admin_username:
to_riak_admin_username_password:
to_riak_uri: "https://riak1.kabletown.invalid:8088"
