# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# Build trafficcontrol:  
#   Copy the traffic_ops rpm to traffic_ops/traffic_ops.rpm
#   Copy the trafficcontrol-cache-config rpm to ort_test/trafficcontrol-cache-config.rpm
#   Copy an ATS rpm to yumserver/test-rpms (the ort_tests
#     container updates ../ort-tests/tc-fixtures.json with
#     the corresponding version string)
#
#   Run: docker compose build
#   Run: docker compose run ort_test
#

---

volumes:
  trafficcontrol:
  traffic_ops:
  conf:

services:
  db:
    image: postgres:13.2
    env_file:
      - variables.env
    ports: 
      - "5432:5432"

  db_init:
    env_file:
      - variables.env
    build:
      context: .
      dockerfile: db_init/Dockerfile
    depends_on: 
      - db

  health-check-test:
    env_file:
      - variables.env
    build:
      context: .
      dockerfile: health-check-test/Dockerfile
      args:
        - OS_DISTRO=${OS_DISTRO:-rockylinux}
        - OS_VERSION=${OS_VERSION:-8}
    depends_on: 
      - to_server
    volumes:
      - ../../..:/root/go/src/github.com/apache/trafficcontrol

  to_server:
    env_file:
      - variables.env
    ports: 
      - "443:443"
    build:
      context: .
      dockerfile: traffic_ops/Dockerfile
      args:
        - OS_DISTRO=${OS_DISTRO:-rockylinux}
        - OS_VERSION=${OS_VERSION:-8}
    volumes:
      - ../../../GO_VERSION:/GO_VERSION
    depends_on:
      - db_init

