---
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
install_traffic_monitor: False
tm_pkg_name: "{% if tm_version is defined and tm_version != omit %}{{ 'traffic_monitor-'+tm_version }}{% else %}traffic_monitor{% endif %}"

# Traffic Monitor installation information
tm_base_dir: '/opt/traffic_monitor'
tm_log_dir: '/var/log/traffic_monitor'
tm_exec_path: "{{ tm_base_dir}}/bin/traffic_monitor"
tm_to_config: "{{ tm_base_dir}}/conf/traffic_ops.cfg"
tm_config: "{{ tm_base_dir}}/conf/traffic_monitor.cfg"
tm_pid_file: "{{ tm_base_dir}}/var/run/traffic_monitor"

# Local OS User for the Traffic Monitor process
tm_user: traffic_monitor
tm_group: traffic_monitor

# traffic_monitor.cfg
tm_monitor_config_polling_interval_ms: 5000
tm_http_timeout_ms: 2000
tm_peer_optimistic_quorum_min: 0
tm_stat_polling: true
tm_distributed_polling: false
tm_max_events: 200
tm_health_flush_interval_ms: 20
tm_log_location_error: "{{ tm_log_dir }}/traffic_monitor.log"
tm_log_location_warning: "{{ tm_log_dir }}/traffic_monitor.log"
tm_log_location_info: "null"
tm_log_location_debug: "null"
tm_log_location_access: "{{ tm_log_dir }}/access.log"
tm_log_location_event: "{{ tm_log_dir }}/event.log"
tm_stat_flush_interval_ms: 20
tm_serve_read_timeout_ms: 10000
tm_serve_write_timeout_ms: 20000
tm_http_polling_format: "text/json"
tm_to_min_retry_interval: 100
tm_to_max_retry_interval: 60000
tm_static_file_dir: "{{ tm_base_dir}}/static"

# traffic_ops.cfg
tm_traffic_ops_username: 'tmuser'
tm_traffic_ops_password: ''
tm_traffic_ops_url: 'https://localhost'
tm_traffic_ops_allow_insecure: true
tm_traffic_ops_target_cdn: 'some-cdn'
tm_traffic_ops_http_listener: ':80'
