# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# This container provide an OpenVPN service.
# It could let user or developer easily access CIAB network.
#
# To start up CiaB with OpenVPN optional container:
#
# alias mydc="docker compose "` \
#   `"-f $PWD/docker-compose.yml "` \
#   `"-f $PWD/docker-compose.expose-ports.yml "` \
#   `"-f $PWD/optional/docker-compose.vpn.yml "` \
#   `"-f $PWD/optional/docker-compose.vpn.expose-ports.yml "
#
# mydc rm -fv
# mydc up
#
# All certificates, keys, and client configuration are stored
# at infrastruture/cdn-in-a-box/optional/vpn/vpnca
# You just simply change ``REALHOSTIP`` and ``REALPORT`` of
# ``client.ovpn`` to fit your environment, and then you can
# connect to this OpenVPN server by it.

---

services:
  vpn:
    build:
      context: .
      dockerfile: optional/vpn/Dockerfile
    hostname: vpn
    domainname: infra.ciab.test
    privileged: true
    depends_on:
      - dns
    env_file:
      - variables.env
    volumes:
      - ./optional/vpn/vpnca:/vpnca
      - shared:/shared

volumes:
  schemas:
    external: false
  shared:
    external: false
