# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# Exposes debugging ports

---
version: '2.1'

services:
  trafficmonitor:
    build:
      context: .
      dockerfile: traffic_monitor/Dockerfile-debug
    image: trafficmonitor-debug
    ports:
      - "2344:2344" #Delve debugging port
    depends_on:
      - trafficmonitor-nondebug
  trafficops:
    build:
      context: .
      dockerfile: traffic_ops/Dockerfile-go-debug
    image: trafficops-go-debug
    ports:
      - "2345:2345" #Delve debugging port
    depends_on:
      - trafficops-go-nondebug
  # The trafficmonitor-nondebug service exists to ensure that the trafficmonitor
  # base image exists before building trafficmonitor-debug.
  trafficmonitor-nondebug:
    image: trafficmonitor
    build:
      context: .
      dockerfile: traffic_monitor/Dockerfile
      args:
        TRAFFIC_MONITOR_RPM: traffic_monitor/traffic_monitor.rpm
    command: /usr/bin/true
  # The trafficops-go-nondebug service ensures that the trafficops-go base image
  # exists before trying to build trafficops-go-debug.
  trafficops-go-nondebug:
    image: trafficops-go
    build:
      context: ../..
      dockerfile: infrastructure/cdn-in-a-box/traffic_ops/Dockerfile-go
      args:
        TRAFFIC_OPS_RPM: infrastructure/cdn-in-a-box/traffic_ops/traffic_ops.rpm
    command: /usr/bin/true
